### ISSUE TITLE
我要進 Google！！！

### ISSUE THREAD

**Issue by aesophor** [a19990506/Leetcode#1]
我的目標是喝到一瓶這邊的飲料XDDDD

![image](https://user-images.githubusercontent.com/32998585/54253218-f7fe0780-4588-11e9-8cb9-a93f64a17a43.png)

**Comment by aesophor** [comment]
wow

**Comment by anitaHey** [comment]
我要喝60瓶!!!!
一天一瓶XDDDDD

**Comment by anitaHey** [comment]
種類好多哦QQQQ感覺好爽

**Comment by aesophor** [comment]
剛剛收到mail
還以爲是要面試了 結果是這個issue的通知XDDDD

**Comment by anitaHey** [comment]
幹XDDDDDD你也害我以為是google的信哈哈哈哈哈哈哈
笑死XDDDD

**Comment by aesophor** [comment]
好緊張哦靠

**Comment by anitaHey** [comment]
可以啦XDDD你害我看到新email緊張了一下哈哈哈哈XDDDDDDD

**Comment by aesophor** [comment]
https://www.youtube.com/watch?v=ETMPuyrZdp0&t=79s

Google 快寄信來啊啊啊

**Comment by aesophor** [comment]
加油啊！！！！
一起去喝飲料！！！！！！
我想去吃那邊的餐廳QQQQ

**Comment by aesophor** [comment]
還有看PLJJ
XDDDDDDDDDDD

**Comment by anitaHey** [comment]
PLJJ!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by aesophor** [comment]
大神加油！！！ :eyes: :eyes: :eyes:

**Comment by anitaHey** [comment]
Rrrrrrrrrrr

**Comment by aesophor** [comment]
哇
